"""Phase 3/4: write the .memory/ layer — graph.json, per-file summaries, index.md."""

from __future__ import annotations

import json
import hashlib
import os
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

import networkx as nx

from .graph_builder import graph_to_json

INDEX_TEMPLATE = """# Codebase Memory (.memory/)

Generated by CMS on {generated}.

This folder is a structural + semantic map of the codebase, built for AI agents
(and humans) to understand where things live before reading raw code.

## Contents

| File | What it is |
|---|---|
| `clean_tree.md` | Filtered directory tree with per-file line counts, sizes, languages |
| `clean_tree.json` | Machine-readable version with full metadata |
| `graph.json` | Knowledge graph: file/class/function nodes with summaries, connected by CONTAINS / IMPORTS / CALLS / INHERITS edges |
| `summaries/` | Per-file low-resolution summaries as readable markdown |
| `features/` | Feature traces: flow, inputs/outputs, verification checklist per feature |

## Stats

- Files scanned: {file_count}
- Graph nodes: {node_count} · edges: {edge_count}
- Summarized files: {summary_count}

## How to query

```bash
cms query "where is the ignore pattern filtering logic?"
```

```python
from cms import CodebaseMemory

mem = CodebaseMemory.load(".memory/graph.json")
for hit in mem.query_intent("clean directory tree building", top_k=5):
    print(hit.path, hit.lines, hit.summary)
```

## Commit or ignore?

Your call: commit `.memory/` so agents always have the map after cloning, or
add it to `.gitignore` and regenerate locally with `cms run-all`.
"""


def export_graph(graph: nx.DiGraph, memory_dir: Path) -> Path:
    memory_dir.mkdir(parents=True, exist_ok=True)
    out = memory_dir / "graph.json"
    # atomic replace: the UI server may be reading while the watcher writes;
    # unique temp name + retry so CONCURRENT writers can't truncate each
    # other's temp file mid-replace (Windows PermissionError race)
    from .semantic_state import atomic_write_json

    atomic_write_json(out, graph_to_json(graph))
    return out


def export_summaries(graph: nx.DiGraph, memory_dir: Path) -> int:
    """One markdown file per summarized source file, mirroring the source layout."""
    summaries_dir = memory_dir / "summaries"
    documents = {}
    for node_id, attrs in graph.nodes(data=True):
        if attrs.get("type") != "file" or not attrs.get("summary"):
            continue
        rel = attrs["path"]
        provider = (attrs.get("summary_meta") or {}).get("provider", "?")
        documents[rel + ".md"] = (
            f"# {rel}\n\n"
            f"*{attrs.get('line_count', '?')} lines · provider: {provider}*\n\n"
            f"{attrs['summary']}\n"
        )
    _reconcile_exports(summaries_dir, documents, "summaries")
    return len(documents)


def export_features(graph: nx.DiGraph, memory_dir: Path) -> int:
    """One markdown trace per feature under .memory/features/."""
    from .features import get_features

    features = get_features(graph)
    features_dir = memory_dir / "features"
    documents = {}
    toc = ["# Feature Traces\n"]
    safe_names = ["".join(c if c.isalnum() or c in "-_" else "_" for c in f["name"]) for f in features]
    for f in features:
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in f["name"])
        if sum(s.casefold() == safe.casefold() for s in safe_names) > 1 or safe.upper() in {
            "README", "CON", "PRN", "AUX", "NUL", *(f"COM{i}" for i in range(1, 10)), *(f"LPT{i}" for i in range(1, 10))
        }:
            safe += "-" + hashlib.sha256(f["name"].encode()).hexdigest()[:10]
        member_lines = "\n".join(f"- `{m}`" for m in f.get("members", []))
        documents[f"{safe}.md"] = (
            f"# Feature: {f['name']}\n\n"
            f"*source: {f.get('source', '?')}"
            + (f" · connects: {', '.join(f['connects'])}" if f.get("connects") else "")
            + "*\n\n"
            + (f"> {f['description']}\n\n" if f.get("description") else "")
            + f"{f.get('summary', '')}\n\n"
            f"## Members\n{member_lines}\n"
        )
        toc.append(f"- [{f['name']}]({safe}.md) — {f.get('description') or f.get('source', '')}")
    documents["README.md"] = "\n".join(toc) + "\n"
    _reconcile_exports(features_dir, documents, "features")
    return len(features)


EXPORT_MANIFEST = ".atlas-generated.json"


def _export_target(directory: Path, rel: str) -> Path:
    target = (directory / rel).resolve()
    if directory.resolve() not in target.parents:
        raise ValueError(f"Invalid generated export path: {rel!r}")
    return target


def _reconcile_exports(directory: Path, documents: dict[str, str], kind: str) -> None:
    """Prune only known generated outputs, preserving unrelated/edited files.

    A content manifest supports safe ownership migration and lets bundles omit
    obsolete user-edited copies that we deliberately preserve on local disk.
    """
    from .semantic_state import atomic_write_json

    directory.mkdir(parents=True, exist_ok=True)
    manifest = directory / EXPORT_MANIFEST
    previous = {}
    if manifest.is_file():
        record = json.loads(manifest.read_text(encoding="utf-8"))
        if not isinstance(record, dict) or not isinstance(record.get("files"), dict):
            raise ValueError(f"Invalid generated export manifest: {manifest}")
        previous = record["files"]
    else:
        # Older Atlas versions lack a manifest. Their exact generated heading
        # shapes identify owned artifacts; arbitrary Markdown is never adopted.
        for path in directory.rglob("*.md"):
            if not path.is_file() or path.is_symlink():
                continue
            body = path.read_text(encoding="utf-8", errors="replace")
            owned = (bool(re.match(r"^# .+\n\n\*[^\n]*provider: [^\n]*\*\n", body))
                     if kind == "summaries" else
                     bool(re.match(r"^# Feature: .+\n\n\*source: ", body))
                     or (path.name == "README.md" and body.startswith("# Feature Traces\n")))
            if owned:
                previous[path.relative_to(directory).as_posix()] = hashlib.sha256(path.read_bytes()).hexdigest()

    # Validate all destinations before changing any artifact.
    for rel in documents:
        target = _export_target(directory, rel)
        if target.exists() and rel not in previous:
            raise FileExistsError(f"Refusing to overwrite an untracked export file: {target}")
    current = {}
    for rel, body in documents.items():
        target = _export_target(directory, rel)
        target.parent.mkdir(parents=True, exist_ok=True)
        payload = body.encode("utf-8")
        temporary = target.with_name(target.name + f".{uuid.uuid4().hex}.tmp")
        try:
            temporary.write_bytes(payload)
            os.replace(temporary, target)
        finally:
            temporary.unlink(missing_ok=True)
        current[rel] = hashlib.sha256(payload).hexdigest()
    for rel, digest in previous.items():
        if rel in current:
            continue
        target = _export_target(directory, rel)
        if target.is_file() and hashlib.sha256(target.read_bytes()).hexdigest() == digest:
            target.unlink()
    atomic_write_json(manifest, {"schema_version": 1, "files": current})


def export_index(graph: nx.DiGraph, memory_dir: Path, file_count: int) -> None:
    summary_count = sum(
        1 for _, a in graph.nodes(data=True) if a.get("type") == "file" and a.get("summary")
    )
    (memory_dir / "index.md").write_text(
        INDEX_TEMPLATE.format(
            generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            file_count=file_count,
            node_count=graph.number_of_nodes(),
            edge_count=graph.number_of_edges(),
            summary_count=summary_count,
        ),
        encoding="utf-8",
    )
